name: ci

on: push

jobs:
  check:
    runs-on: codeberg-tiny-lazy
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Mizu
        run: bun i

      - name: Run linters
        run: bun lint

      - name: Run tests
        run: bun test
