import { Icons } from '../utils/icons'

/* eslint max-lines: 0 */
export const icons: Icons = {
  admin: [
    '/admin',
    '/admins',
    '/manager',
    '/managers',
    '/moderator',
    '/moderators',
  ],
  api: [
    '/api',
    '/api_def',
    '/apis',
    '/base_api',
    '/global-api',
    '/openapi',
    '/rest',
    '/rest-api',
    '/restapi',
  ],
  app: [
    '/app',
    '/application',
    '/applications',
    '/apps',
    '/program files (x86)',
    '/program files',
    '/program',
    '/programs',
  ],
  archive: ['/arc', '/archival', '/archive', '/archived', '/archives', '/arcs'],
  binary: [
    '*.aea',
    '*.agc',
    '*.ags',
    '*.argus',
    '*.asm',
    '*.bin',
    '*.binsource',
    '*.inc',
    '*.mitigus',
    '*.nasm',
    '*.s',
  ],
  audio: [
    '/aud',
    '/audio',
    '/audios',
    '/auds',
    '/music',
    '/sound',
    '/sounds',
    '/soundtrack',
    '/soundtracks',
    '*.3ga',
    '*.aa3',
    '*.aac',
    '*.aacp',
    '*.aif',
    '*.aifc',
    '*.aiff',
    '*.amr',
    '*.ape',
    '*.at3',
    '*.at9',
    '*.atp',
    '*.au',
    '*.caf',
    '*.flac',
    '*.hma',
    '*.lbc',
    '*.m1a',
    '*.m2a',
    '*.m4a',
    '*.m4b',
    '*.mp+',
    '*.mp1',
    '*.mp2',
    '*.mp3',
    '*.mpa',
    '*.mpc',
    '*.mpp',
    '*.mt9',
    '*.ogg',
    '*.oma',
    '*.omg',
    '*.opus',
    '*.pcm',
    '*.qcp',
    '*.ra',
    '*.ram',
    '*.shn',
    '*.sil',
    '*.snd',
    '*.spx',
    '*.tta',
    '*.wav',
    '*.wave',
    '*.wma',
    '*.wv',
    '*.wvc',
  ],
  auth: [
    '/auth',
    '/authenticate',
    '/authenticated',
    '/authentication',
    '/authentications',
    '/cookie',
    '/cookies',
    '/devise',
    '/session',
    '/sessions',
  ],
  benchmark: [
    '/bench',
    '/benchmark',
    '/benchmarks',
    '/measure',
    '/measurement',
    '/measures',
    '/performance',
  ],
  boot: ['/boot'],
  calendar: [
    '/calendar',
    '/calendars',
    '/date',
    '/dates',
    '*.ical',
    '*.icalendar',
    '*.ics',
    '*.ifb',
  ],
  certificate: [
    '/ca-cert',
    '/ca-certificates',
    '/cert',
    '/certificate',
    '/certificates',
    '/certs',
    '/ssl',
    '/ssl-cert',
    '/tls',
    '/verification',
    '/verified',
    '/verify',
  ],
  cloud: ['/.aws', '/aws', '/cloud', '/drive', '/iclouddrive', '/onedrive'],
  code: ['/code', '/main', '/source', '/sources', '/src', '/srcs'],
  component: [
    '/bower_components',
    '/component',
    '/components',
    '/fragment',
    '/fragments',
    '/part',
    '/parts',
  ],
  conduct: [
    'code_of_conduct',
    'code_of_conduct.md',
    'code_of_conduct.rst',
    'code_of_conduct.txt',
  ],
  config: [
    '/.config',
    '/.setting',
    '/.settings',
    '/cfg',
    '/cfgs',
    '/conf',
    '/config',
    '/configs',
    '/configuration',
    '/configurations',
    '/confs',
    '/local settings',
    '/meta-inf',
    '/setting',
    '/settings',
    '*.cfg',
    '*.cnf',
    '*.conf',
    '*.config',
    '*.ini',
    '*.options',
    '*.prefs',
    '*.properties',
    '*.props',
    '*.settings',
  ],
  contact: ['/contact', '/contacts', '/userdata'],
  controller: [
    '/controller',
    '/controllers',
    '/handler',
    '/handlers',
    '/provider',
    '/providers',
  ],
  core: ['/core', '/cores', '/kernel', '/kernels', '*.exe', '*.msi'],
  cron: [
    '/cron',
    '/cron.d',
    '/cron.daily',
    '/cron.hourly',
    '/cron.monthly',
    '/cron.weekly',
    '/cronjob',
    '/cronjobs',
    '/crons',
    '/time',
    '/timer',
  ],
  cursor: ['*.cur'],
  database: [
    '/database',
    '/databases',
    '/db',
    '/dbms',
    '/dbs',
    '/migrate',
    '/migration',
    '/migrations',
    '/queries',
    '/query',
    '/sql',
    '*.db',
    '*.pdb',
    '*.pgsql',
    '*.pkb',
    '*.pks',
    '*.sql',
  ],
  debug: ['/bug', '/bugfix', '/bugfixes', '/bugs', '/debug', '/debugging'],
  default: [],
  desktop: ['/desktop', '/desktops'],
  dist: [
    '/.bin',
    '/bin',
    '/build',
    '/builds',
    '/cgi-bin',
    '/desktop-build',
    '/dist',
    '/dists',
    '/ebin',
    '/out',
    '/output',
    '/outputs',
    '/release',
    '/releases',
    '/sbin',
    '/usrbin',
  ],
  doc: [
    '/doc',
    '/docs',
    '/document',
    '/documentation',
    '/documentations',
    '/documents',
    '/markdown',
    '/md',
    '/my documents',
  ],
  download: [
    '/dl',
    '/dls',
    '/download',
    '/downloader',
    '/downloaders',
    '/downloads',
    '/install',
    '/installed',
    '/installer',
    '/installers',
    '/installs',
  ],
  email: ['*.eml', '*.emlx', '*.mbx', '*.msg', '.mailmap'],
  environment: [
    '/.env',
    '/.venv',
    '/devenvironments',
    '/env',
    '/environment',
    '/environments',
    '/envs',
    '/venv',
    '/venvs',
    '/virtualenv',
    '*.env',
    '.env.defaults',
    '.env.dev',
    '.env.development',
    '.env.dist',
    '.env.example',
    '.env.prod',
    '.env.production',
    '.env.sample',
    '.env.template',
    '.env.test',
  ],
  error: [
    '/crash',
    '/crashes',
    '/crashing',
    '/err',
    '/error',
    '/error-codes',
    '/errorcodes',
    '/errors',
    '/errs',
    '/exception',
    '/exceptions',
    '/fail',
    '/failed',
    '/fails',
  ],
  etc: [
    '/alt',
    '/alternative',
    '/alternatives',
    '/alts',
    '/etc',
    '/extra',
    '/extras',
    '/misc',
    '/miscellaneous',
    '/more',
    '/other',
    '/others',
  ],
  event: ['/config_states', '/event', '/events', '/state', '/states'],
  example: [
    '/demo',
    '/demos',
    '/example',
    '/examples',
    '/idea',
    '/ideas',
    '/sample',
    '/sample-data',
    '/samples',
  ],
  experimental: [
    '/experiment',
    '/experimental',
    '/experimentals',
    '/experimenting',
  ],
  export: ['/export', '/exported', '/exports'],
  factory: ['/factories', '/factory'],
  favicon: [
    '/favicon',
    '/favicons',
    'favicon.ico',
    'favicon.png',
    'favicon.svg',
    'favicon.webp',
  ],
  feedback: ['/feedback', '/feedbacks', '/support'],
  file: [
    '/asset',
    '/assets',
    '/file',
    '/filedata',
    '/files',
    '/res',
    '/resource',
    '/resources',
    '/static',
  ],
  filter: ['/filter', '/filters'],
  folder: ['/dir', '/directories', '/directory', '/folder', '/folders'],
  font: [
    '/fnt',
    '/fnts',
    '/font',
    '/fonts',
    '*.dfont',
    '*.eot',
    '*.fnt',
    '*.odttf',
    '*.otf',
    '*.pfa',
    '*.pfb',
    '*.t11',
    '*.t42',
    '*.ttc',
    '*.tte',
    '*.ttf',
    '*.ttf.bin',
    '*.ufo',
    '*.ufo2',
    '*.ufo3',
    '*.woff',
    '*.woff2',
  ],
  game: ['/game', '/games', '/gaming', '/saved games', '/xboxgames'],
  generator: [
    '/auto',
    '/autoload',
    '/autoloader',
    '/autostart',
    '/cfn-gen',
    '/gen',
    '/generate',
    '/generated',
    '/generator',
    '/generators',
    '/gens',
  ],
  global: [
    '/browser',
    '/browsers',
    '/g11n',
    '/global',
    '/globalisation',
    '/globalization',
    '/globals',
    '/public',
    '/site',
    '/web',
    '/website',
    '/www',
    '/wwwroot',
  ],
  group: [
    '/communities',
    '/community',
    '/customer',
    '/customers',
    '/friend',
    '/friends',
    '/group',
    '/groups',
  ],
  guard: ['/guard', '/guards', '/secure', '/security'],
  home: ['/home', '/menu', '/start menu', '/start'],
  image: [
    '/_image',
    '/_images',
    '/_img',
    '/_imgs',
    '/accountpictures',
    '/avatar',
    '/avatars',
    '/brand',
    '/branding',
    '/brands',
    '/fig',
    '/figs',
    '/figure',
    '/figures',
    '/image',
    '/images',
    '/img',
    '/imgs',
    '/logo',
    '/logos',
    '/m',
    '/media',
    '/my pictures',
    '/pfp',
    '/pfps',
    '/photo',
    '/photos',
    '/pic',
    '/pics',
    '/picture',
    '/pictures',
    '/screengrab',
    '/screengrabs',
    '/screenshot',
    '/screenshots',
    '*.afphoto',
    '*.apng',
    '*.apx',
    '*.ase',
    '*.aseprite',
    '*.avci',
    '*.avcs',
    '*.avif',
    '*.avifs',
    '*.bmp',
    '*.bpg',
    '*.brk',
    '*.clip',
    '*.cpt',
    '*.dds',
    '*.dib',
    '*.djv',
    '*.djvu',
    '*.dng',
    '*.eps',
    '*.exr',
    '*.flif',
    '*.fpx',
    '*.gbr',
    '*.gif',
    '*.hdp',
    '*.heic',
    '*.heics',
    '*.heif',
    '*.heifs',
    '*.icns',
    '*.ico',
    '*.img',
    '*.j2c',
    '*.j2k',
    '*.jb2',
    '*.jbg',
    '*.jbig',
    '*.jbig2',
    '*.jfi',
    '*.jfif',
    '*.jif',
    '*.jng',
    '*.jp2',
    '*.jpc',
    '*.jpe',
    '*.jpeg',
    '*.jpf',
    '*.jpg',
    '*.jpg2',
    '*.jpm',
    '*.jpx',
    '*.jxl',
    '*.jxr',
    '*.jxs',
    '*.kra',
    '*.mdp',
    '*.mng',
    '*.ora',
    '*.pbm',
    '*.pdn',
    '*.pgf',
    '*.pgm',
    '*.pic',
    '*.png',
    '*.pnm',
    '*.ppm',
    '*.qoi',
    '*.qtvr',
    '*.raw',
    '*.sai',
    '*.sai2',
    '*.six',
    '*.sixel',
    '*.tga',
    '*.tif',
    '*.tiff',
    '*.wbmp',
    '*.wdp',
    '*.webp',
    '*.wp2',
    '*.xcf',
  ],
  import: [
    '/_includes',
    '/_partials',
    '/import',
    '/imported',
    '/imports',
    '/in',
    '/inc',
    '/include',
    '/includes',
    '/partial',
    '/partials',
  ],
  initialize: [
    '/init',
    '/initialize',
    '/initializer',
    '/initializers',
    '/inits',
  ],
  iso: ['*.iso'],
  job: ['/job', '/jobs'],
  key: [
    '/jwt',
    '/key',
    '/keys',
    '/tkn',
    '/token',
    '/tokens',
    '*.asc',
    '*.gpg',
    '*.key',
    '*.pem',
    '*.pub',
    '.htpasswd',
  ],
  layer: ['/layer', '/layers'],
  lib: [
    '/lib',
    '/lib32',
    '/lib64',
    '/libraries',
    '/library',
    '/libs',
    '/libx32',
  ],
  license: [
    'authors',
    'codeowners',
    'copyright',
    'copyright.txt',
    'licence',
    'license',
    'license.md',
    'license.rst',
    'license.txt',
    'patent_grant',
  ],
  like: ['/fav', '/favorite', '/favorites', '/favs', '/like', '/likes'],
  link: ['/link', '/links', '/url', '/urls', '*.url'],
  lint: ['lint'],
  locale: [
    '/i18n',
    '/internationalization',
    '/internationalizations',
    '/intl',
    '/intls',
    '/l10n',
    '/lang',
    '/langs',
    '/language',
    '/languages',
    '/locale',
    '/locales',
    '/localization',
    '/localizations',
    '/translate',
    '/translation',
    '/translations',
  ],
  lock: [
    '/.private',
    '/_private',
    '/hidden',
    '/lock',
    '/locked',
    '/priv',
    '/private',
    '*.enc',
    '*.lock',
    'security',
    'security.md',
    'security.txt',
  ],
  log: ['/_logs', '/log', '/logging', '/logs', '*.log'],
  login: [
    '/login',
    '/logins',
    '/registration',
    '/registrations',
    '/signup',
    '/signups',
  ],
  mail: [
    '/email',
    '/emails',
    '/mail',
    '/mailer',
    '/mailers',
    '/mailoutput',
    '/mails',
    '/mailtodisk',
    '/phpmailer',
    '/smtp',
  ],
  mobile: [
    '/client',
    '/clients',
    '/front-end',
    '/frontend',
    '/mobile',
    '/mobiles',
    '/portability',
    '/portable',
    '/pwa',
    '/webapp',
  ],
  mock: [
    '/__mocks__',
    '/_draft',
    '/_drafts',
    '/concept',
    '/concepts',
    '/draft',
    '/drafts',
    '/fixture',
    '/fixtures',
    '/mock',
    '/mocks',
    '/mockup',
    '/mockups',
    '/sketch',
    '/sketches',
  ],
  model: [
    '/class',
    '/classes',
    '/model',
    '/models',
    '/schema',
    '/schemas',
    '*.drawio',
  ],
  music: [
    '*.als',
    '*.dmpatch',
    '*.fst',
    '*.mid',
    '*.ppsf',
    '*.vpr',
    '*.vsq',
    '*.vsqx',
  ],
  password: ['/password', '/passwords', '/pwd', '/pwds'],
  payment: [
    '/banking',
    '/finance',
    '/finances',
    '/income',
    '/money',
    '/payment',
    '/payments',
    '/revenue',
    '/tax',
    '/taxes',
  ],
  plugin: [
    '/addon',
    '/addons',
    '/builtin',
    '/extension',
    '/extensions',
    '/extensions-builtin',
    '/middleware',
    '/middlewares',
    '/mod',
    '/module',
    '/modules',
    '/plugin',
    '/plugins',
  ],
  post: [
    '/chat',
    '/chats',
    '/conversation',
    '/conversations',
    '/forum',
    '/forums',
    '/message',
    '/messages',
    '/messaging',
    '/msg',
    '/msgs',
    '/post',
    '/posts',
  ],
  readme: ['readme', 'readme.md', 'readme.rst', 'readme.txt'],
  repository: ['/repo', '/repos', '/repositories', '/repository'],
  restore: ['/recover', '/recovery', '/restore', '/restored'],
  review: ['/review', '/reviewed', '/reviews', '/revisal', '/revisals'],
  robot: [
    '/ai',
    '/ai-art',
    '/codeformer',
    '/dalle',
    '/deepbooru',
    '/esrgan',
    '/gfpgan',
    '/gpt',
    '/lora',
    '/stable-diffusion',
    '/swinir',
    '/vae',
    '/vae-approx',
    'robots.txt',
  ],
  role: ['/role', '/roles', '/userroles'],
  root: ['/root', '/roots'],
  route: ['/route', '/router', '/routers', '/routes'],
  run: [
    '/common_runtime',
    '/distributed_runtime',
    '/run',
    '/runner',
    '/runner.xcodeproj',
    '/runner.xcworkspace',
    '/runtime',
    '/runtime_client',
    'run',
  ],
  save: ['/bookmark', '/bookmarks', '/save', '/saved', '/saving'],
  script: ['/build_scripts', '/script', '/scripts'],
  search: ['/lost+found', '/search', '/searches'],
  server: [
    '/api-server',
    '/back-end',
    '/backend',
    '/server',
    '/servers',
    '*.pid',
  ],
  service: ['/service', '/services'],
  setup: ['setup'],
  shader: ['/glsl', '/hlsl', '/shader', '/shaders'],
  share: [
    '/common',
    '/commons',
    '/redirect',
    '/redirects',
    '/sendto',
    '/share',
    '/shared',
    '/sharing',
  ],
  spreadsheet: ['*.csv', '*.ods', '*.psv', '*.tsv'],
  stats: [
    '/diagram',
    '/diagrams',
    '/excel',
    '/numbers',
    '/stat',
    '/statistic',
    '/statistics',
    '/stats',
    '*.numbers',
  ],
  storage: [
    '/back-up',
    '/back-ups',
    '/backup',
    '/backups',
    '/bak',
    '/baks',
    '/bk',
    '/bkp',
    '/bkps',
    '/dump',
    '/dumps',
    '/storage',
    '/storages',
    '/store',
    '/stores',
    '/syncbackup',
  ],
  syntax: ['/spellcheck', '/spellchecks', '/syntax', '/syntaxes'],
  target: ['/target', '/tgt'],
  task: [
    '/task',
    '/tasks',
    '/ticket',
    '/tickets',
    '/todo',
    '/todos',
    '*.todo',
    'todo',
    'todo.md',
    'todo.rst',
    'todo.txt',
    'todos',
    'todos.md',
    'todos.rst',
    'todos.txt',
  ],
  template: ['/_template', '/_templates', '/templ', '/template', '/templates'],
  temporary: [
    '/.cache',
    '/.pkg-cache',
    '/.temp',
    '/.tmp',
    '/aitemp',
    '/cache',
    '/cached',
    '/onedrivetemp',
    '/package cache',
    '/systemtemp',
    '/temp',
    '/temporary',
    '/tmp',
  ],
  test: [
    '/.test',
    '/.testing',
    '/.tests',
    '/__test__',
    '/__tests__',
    '/_test',
    '/_tests',
    '/boot-tests',
    '/boot_tests',
    '/coverage',
    '/dts-test',
    '/e2e',
    '/e2e-test',
    '/e2e-tests',
    '/integration-test',
    '/integration-testing',
    '/integration-tests',
    '/integration_test',
    '/integration_testing',
    '/integration_tests',
    '/it',
    '/kernel-tests',
    '/kernel_tests',
    '/memory-tests',
    '/memory_tests',
    '/runnertests',
    '/spec',
    '/specs',
    '/test',
    '/testing',
    '/tests',
    '/unit',
    '/unit-test',
    '/unit-tests',
    '/unit_test',
    '/unit_tests',
    'check',
    'test',
  ],
  text: ['*.txt'],
  texture: ['/texture', '/textures'],
  theme: ['/color', '/colors', '/design', '/designs', '/theme', '/themes'],
  threed: [
    '*.3d',
    '*.ac',
    '*.blend',
    '*.fbx',
    '*.kv6',
    '*.mesh',
    '*.mqo',
    '*.obj',
    '*.pmd',
    '*.pmx',
    '*.skp',
    '*.stl',
    '*.stp',
    '*.vac',
    '*.vox',
    '*.voxb',
    '*.x',
  ],
  tool: ['/tool', '/toolbox', '/toolboxes', '/toolkit', '/toolkits', '/tools'],
  trash: ['/.trash', '/delete', '/dev/null', '/remove', '/removed', '/trash'],
  tutorial: [
    '/howto',
    '/howtos',
    '/intro',
    '/introduction',
    '/introductions',
    '/intros',
    '/learn',
    '/learning',
    '/tutorial',
    '/tutorials',
  ],
  upload: ['/upload', '/uploader', '/uploaders', '/uploads'],
  user: ['/all users', '/default user', '/personal', '/user', '/users', '/usr'],
  util: ['/test-utils', '/util', '/utilities', '/utility', '/utils'],
  vendor: ['/third-party', '/third_party', '/vendor', '/vendors'],
  version: [
    '/changelog',
    '/changelogs',
    'changelog',
    'changelog.md',
    'changelog.rst',
    'changelog.txt',
    'changes',
    'changes.md',
    'changes.rst',
    'changes.txt',
    'version',
    'version.md',
    'version.rst',
    'version.txt',
  ],
  video: [
    '/caps',
    '/captures',
    '/mov',
    '/movie',
    '/movies',
    '/my videos',
    '/v',
    '/vid',
    '/video',
    '/videos',
    '/vids',
    '*.3g2',
    '*.3gp',
    '*.av1',
    '*.avc1',
    '*.avchd',
    '*.avi',
    '*.bik',
    '*.bk2',
    '*.f4v',
    '*.flv',
    '*.gifv',
    '*.hevc',
    '*.ivf',
    '*.m1v',
    '*.m2v',
    '*.m4p',
    '*.m4r',
    '*.m4v',
    '*.mj2',
    '*.mjp2',
    '*.mkv',
    '*.mov',
    '*.mp4',
    '*.mpe',
    '*.mpeg',
    '*.mpg',
    '*.mpv',
    '*.ogv',
    '*.qt',
    '*.rm',
    '*.rmvb',
    '*.smk',
    '*.swf',
    '*.vob',
    '*.webm',
    '*.wmv',
    '*.yuv',
  ],
  widget: ['/widget', '/widgets'],
  work: ['/biz', '/business', '/work', '/worker', '/workers', '/working'],
  workspace: ['*.workspace', 'workspace'],
  wrapper: ['/wrap', '/wrapper', '/wrappers'],
  zip: [
    '*.7z',
    '*.a',
    '*.ace',
    '*.ar',
    '*.arc',
    '*.br',
    '*.bz2',
    '*.bzip2',
    '*.cpio',
    '*.gz',
    '*.gzip',
    '*.lbr',
    '*.lz',
    '*.lz4',
    '*.lzma',
    '*.lzo',
    '*.rar',
    '*.rz',
    '*.s7z',
    '*.sbx',
    '*.sfark',
    '*.shar',
    '*.sz',
    '*.tar',
    '*.tbz2',
    '*.tgz',
    '*.tlz',
    '*.txz',
    '*.tz',
    '*.xz',
    '*.z',
    '*.zip',
    '*.zipx',
    '*.zst',
  ],
}
