import type { Icons } from '../utils/icons'

/* eslint max-lines: 0 */
export const logos: Icons = {
  access: [
    '*.accda',
    '*.accdb',
    '*.accde',
    '*.accdr',
    '*.accdt',
    '*.adn',
    '*.laccdb',
    '*.maf',
    '*.mam',
    '*.maq',
    '*.mar',
    '*.mdb',
    '*.mdw',
  ],
  actionscript: ['*.as'],
  ada: ['*.ad(a|b|s)'],
  adobe: ['/(adobe|creative cloud files)'],
  aftereffects: ['*.aep'],
  agda: ['*.l?agda'],
  android: [
    '/.android',
    '/android',
    '/androidstudioprojects',
    '/apk',
    '*.aab',
    '*.apk',
    '*.apkm',
    '*.apks',
    '*.dex',
    '*.smali',
    '*.xapk',
    'androidmanifest.xml',
  ],
  angular: ['(.angular-cli|angular-cli|angular|ng-package).json'],
  antlr: ['*.g4'],
  apache: ['.htaccess'],
  applescript: ['*.(scpt|scptd|applescript|ipa)'],
  appveyor: ['appveyor.yml'],
  arduino: ['*.ino'],
  aspnet: ['*.(asp|aspx|cshtml|razor|vbhtml)'],
  astro: ['*.astro'],
  astroConfig: ['astro.config.(js|cjs|mjs|ts)'],
  audition: ['*.sesx'],
  aurelia: ['aurelia.json'],
  autohotkey: ['*.ahk'],
  autoit: ['*.au3'],
  azure: ['/(.azure|.azure-pipelines|.azure-pipelines-ci|azure)'],
  babel: [
    '.babel-plugin-macrosrc(|.js|.json|.yml|.yaml)',
    '.babelrc(|.js|.cjs|.mjs|.json)',
    'babel-plugin-macros.config.(|c|m)js',
    'babel-transform.(js|cjs|mjs|ts)',
    'babel.config.(js|cjs|mjs|json)',
  ],
  ballerina: ['*.bal', '*.balx'],
  batch: ['*.bat', '*.btm', '*.cmd'],
  bazel: ['*.bzl', '*.bazel', '.bazelrc', '.bazelversion'],
  bazelIgnore: ['.bazelignore'],
  bitbucket: ['bitbucket-pipelines.ya?ml'],
  bithound: ['.bithoundrc'],
  bloc: ['/bloc'],
  brainfuck: ['*.bf?'],
  browserslist: ['(.browserslistrc|browserslist)'],
  buildkite: ['/.?buildkite', 'buildkite.ya?ml'],
  bun: ['/.?bun', 'bunfig.toml'],
  bunLock: ['bun.lockb'],
  c: ['/c', '*.c'],
  caddy: ['caddyfile'],
  cake: ['*.cake', 'cakefile'],
  carbon: ['*.carbon'],
  cargo: ['/(.cargo|cargo|crates)', 'cargo.toml'],
  cargoLock: ['cargo.lock'],
  ceylon: ['*.ceylon'],
  circleci: ['/.?circleci'],
  clean: ['*.(abc|dcl|icl)'],
  clojure: ['*.clj(|c|s|x)', '*.edn'],
  cloudfoundry: ['.cfignore'],
  cmake: ['/cmake(|tools)'],
  cobol: ['*.(cbl|cob|cpy)'],
  codeclimate: ['.codeclimate.(json|yml)'],
  coffeescript: ['*.(coffee|litcoffee|cjsx)'],
  coldfusion: ['*.cf(c|m|ml)', '*.lucee'],
  composer: ['/composer'],
  cpp: ['/(c++|cpp|cxx)', '*.(c++|cc|cpp|cxx)(|m)', '*.(cp|ipp|ixx)'],
  crystal: ['*.cr'],
  csharp: ['*.csx?'],
  css: ['/(style|stylesheet)s?', '/css', '*.css'],
  cssApp: ['app(|lication).css'],
  cssMap: ['*.css.map'],
  cssRtl: ['*.rtl(|.min).css'],
  cucumber: ['*.feature'],
  cuda: ['*.cuh?'],
  cypress: [
    '/.?cypress',
    'cypress.config.(js|cjs|mjs|ts|json)',
    'cypress.env.json',
  ],
  d: ['*.d'],
  dart: [
    '/.dart(|-tool|_tool)',
    '/(.flutter-devtools|dart|flutter)',
    '*.dart',
    'dart',
  ],
  dartIgnore: ['.(dartignore|pubignore)'],
  deno: ['deno.jsonc?'],
  denoLock: ['deno.lock'],
  dependabot: ['dependabot.ya?ml'],
  docker: [
    '/(.docker|docker|dockerfiles)',
    '*.dockerfile',
    '(containerfile|dockerfile|docker-compose.ya?ml|docker-entrypoint.sh)',
  ],
  dockerIgnore: ['.dockerignore'],
  dot: ['*.(dot|jst)'],
  dropbox: ['/dropbox'],
  dylan: ['*.(dyl|dylan|lid)'],
  editorconfig: ['.editorconfig'],
  eiffel: ['*.e'],
  elixir: ['/(.mix|mix|elixir)', '*.(ex|exs|eex|heex|leex)'],
  elixirLock: ['mix.lock'],
  elm: ['*.elm'],
  ember: ['.ember-cli(|.js)', 'ember-cli-builds.js'],
  epub: ['*.epub'],
  erlang: ['*.(e|h)rl'],
  eslint: ['.eslintrc.(js|cjs|json|yml|yaml)', 'eslint.config.(|c|m)js'],
  eslintIgnore: ['.eslintignore'],
  excel: [
    '*.xla',
    '*.xlam',
    '*.xlb',
    '*.xlc',
    '*.xld',
    '*.xlk',
    '*.xll',
    '*.xlm',
    '*.xlsb',
    '*.xlsm',
    '*.xlsx',
    '*.xlt',
    '*.xltm',
    '*.xlv',
    '*.xlw',
  ],
  fastlane: ['(app|fast)file'],
  figma: ['*.fig'],
  firebase: [
    '/.?firebase',
    '(.firebaserc|firebase.json)',
    'firestore.(indexes.json|rules)',
  ],
  forgejo: ['/.?forgejo'],
  forth: ['*.(4th|forth|fth)'],
  fortran: ['*.f(|03|77|90|95|or)'],
  fsharp: ['*.fs', '*.fsi', '*.fsproj', '*.fsscript', '*.fsx'],
  gatsby: [
    'gatsby-browser.js',
    'gatsby-browser.tsx',
    'gatsby-config.js',
    'gatsby-config.mjs',
    'gatsby-config.ts',
    'gatsby-node.js',
    'gatsby-node.mjs',
    'gatsby-node.ts',
    'gatsby-ssr.js',
    'gatsby-ssr.tsx',
  ],
  gemfile: ['gemfile'],
  gemfileLock: ['gemfile.lock'],
  getx: ['/getx'],
  git: [
    '/.git',
    '/.githooks',
    '/.submodules',
    '/commit',
    '/commits',
    '/git',
    '/git-hooks',
    '/githooks',
    '/patches',
    '/submodules',
    '*.patch',
    '.gitattributes',
    '.gitinclude',
    '.gitkeep',
    '.gitmessage',
    '.gitpreserve',
    '.keep',
  ],
  gitConfig: ['.git/config', '.gitconfig'],
  gitIgnore: ['.git-blame-ignore', '.git-blame-ignore-revs', '.gitignore'],
  gitModule: ['.gitmodules'],
  gitea: ['/.?gitea'],
  github: ['/.?github', '/(issue_template|workflows)'],
  gitlab: ['/.?gitlab', '.gitlab-ci.yml'],
  gitpod: ['.gitpod.yml'],
  gnupg: ['/(.gnupg|gnupg|gpg)'],
  go: ['/go(|-build|lang)', '*.go'],
  goMod: ['go.mod', 'go.sum', 'go.work', 'go.work.sum'],
  godot: ['/.godot', '/.godot-cpp', '/godot', '/godot-cpp', '*.gd'],
  gradle: [
    '/.gradle',
    '/gradle',
    '*.gradle',
    'gradle',
    'gradle-wrapper.properties',
    'gradle.properties',
    'gradlew',
  ],
  graphcool: ['*.graphcool'],
  graphql: ['/gql', '/graphql', '*.gql', '*.graphql'],
  graphqlConfig: [
    '.graphqlconfig',
    '.graphql.config.(js|cjs|mjs|ts)',
    '.graphqlrc(|.js|.cjs|.mjs|.ts|.json|.yml|.yaml|.toml)',
  ],
  groovy: ['*.(gy|gvy|groovy)'],
  gulp: ['gulpfile.(js|cjs|mjs|ts)', 'gulpfile.(babel|esm).(js|cjs|mjs|ts)'],
  h: ['*.h'],
  hack: ['*.(hck|hack|hackpartial|hhi)'],
  hackConfig: ['.hhconfig'],
  haml: ['*.haml'],
  handlebars: ['*.(hbs|handlebars)'],
  harbour: ['*.(hb|hbp|prg)'],
  hardhat: ['hardhat.config.(j|t)s'],
  haskell: ['*.(hs|hsc|lhs)'],
  haxe: ['*.hx(|ml)'],
  hcl: ['*.hcl'],
  heroku: ['heroku.yml', 'procfile(|.dev|.prod|.windows)'],
  herokuIgnore: ['.slugignore'],
  hpp: ['*.(h++|hh|hpp|hxx|inl|tcc|tpp|txx)'],
  html: ['/(html|markup)', '/views?', '*.(htm|html|shtml|xhtml)'],
  hy: ['*.hy'],
  idris: ['*.(ibc|idr|lidr)'],
  illustrator: ['*.ai'],
  indesign: ['*.indd'],
  intellij: ['/.idea'],
  ios: ['/ios'],
  java: ['/(java|jvm)', '*.(java|jmod|jsp)'],
  javaClass: ['*.class'],
  javaJar: ['*.jar'],
  jenkins: ['*.jenkins(|file)', 'jenkinsfile'],
  jest: [
    '.jestrc(|.js|.cjs|.mjs)',
    'jest(.|-)e2e.config.(js|cjs|mjs|ts|json)',
    'jest.(config|preset).(js|cjs|mjs|ts|json)',
    'jest.setup.(js|jsx|cjs|mjs|ts|tsx)',
  ],
  jinja: ['*.(j2|jinja|jinja2)'],
  jquery: ['jquery(|.min).js'],
  js: ['/(script|javascript)s?', '/js', '*.(|c|m)js'],
  jsApp: ['app(|lication).(|c|m)js'],
  jsComponent: ['*.component.(|c|m)js'],
  jsConfig: ['*.conf(|ig).(|c|m)js', '(jsconfig.json|manifest.js)'],
  jsController: ['*.controller.(|c|m)js'],
  jsError: ['*.(error|exception).(|c|m)js'],
  jsFilter: ['*.filter.(|c|m)js'],
  jsGuard: ['*.guard.(|c|m)js'],
  jsInitializer: ['*.init.(|c|m)js'],
  jsMain: ['(index|main).(|c|m)js'],
  jsMap: ['*.(|c|m)js.map'],
  jsPipe: ['*.pipe.(|c|m)js'],
  jsServer: ['*.server.(|c|m)js'],
  jsService: ['*.service.(|c|m)js'],
  jsStore: ['*.store.(|c|m)js'],
  jsTest: ['*.(cy.js|js.snap)', '*.(e2e|e2e-spec|spec|test).(|c|m)js'],
  jsWorker: ['(sw|serviceworker|service-worker|worker).js'],
  json: ['/(appdata|data|json)', '*.json(|5|c|l)', '*.ndjson'],
  jsonOther: ['*.(cson|ron|tf.json)'],
  jsr: ['jsr.json'],
  julia: ['/(jl|julia)', '*.jl'],
  jupyter: ['*.ipynb'],
  karma: ['karma.conf(|ig).(coffee|js|ts)'],
  kh: ['*.kh'],
  kotlin: ['*.kt(|m|s)'],
  kubernetes: ['/.?(k8s|kubernetes)'],
  laravel: ['*.(blade|inky).php', 'artisan'],
  less: ['*.less'],
  lerna: ['lerna.json'],
  lighthouse: ['.?lighthouserc.(js|cjs|json|yml|yaml)'],
  lingui: ['lingui.config.js'],
  linux: ['/(arch|linux|ubuntu|wsl|wslg)'],
  lisp: ['*.lisp', '*.lsp'],
  livescript: ['*.ls'],
  lolcode: ['*.lol', '*.lols'],
  lua: ['/lua', '*.lua', '.luacheckrc'],
  makefile: ['*.mk', 'gnumakefile', 'kbuild', 'makefile'],
  markdown: ['*.markdown', '*.md', '*.rmd', '*.rst'],
  markdownLint: ['.mdlrc'],
  marko: ['*.marko'],
  mathematica: ['*.nbp?'],
  matlab: ['*.(m|mat|mlapp|mlappinstall|mlpkginstall|mltbx|mlx)'],
  maven: ['/(.mvn|maven)', '(jvm|maven).config', 'mvnw(|.cmd)', 'pom.xml'],
  mdx: ['*.mdx'],
  mercurial: ['/.hg', '.hgrc'],
  mermaid: ['*.(mermaid|mmd)'],
  minecraft: [
    '*.mca',
    '*.mcaddon',
    '*.mcfunction',
    '*.mcgame',
    '*.mclevel',
    '*.mcmeta',
    '*.mcpack',
    '*.mcproject',
    '*.mcr',
    '*.mcstructure',
    '*.mctemplate',
    '*.mcworld',
    '*.mine',
    '*.mus',
    '.mcattributes',
    '.mcdefinitions',
  ],
  minecraftIgnore: ['.mcignore'],
  mocha: [
    '.mocharc.js',
    '.mocharc.json',
    '.mocharc.jsonc',
    '.mocharc.yaml',
    '.mocharc.yml',
    'mocha.opts',
  ],
  modernizr: ['.modernizrrc', '.modernizrrc.js', '.modernizrrc.json'],
  mojo: ['*.mojo', '*.🔥'],
  nanostaged: ['.?nano-staged.(js|cjs|mjs|json)', '.nanostagedrc'],
  netlify: ['netlify.toml'],
  newrelic: ['newrelic.yml'],
  next: ['next.config.(js|mjs|ts)'],
  nginx: ['/nginx', 'fastcgi.conf', 'mime.types', 'nginx.conf', 'proxy.conf'],
  nim: ['*.nim', '*.nimble', '*.nims'],
  node: ['/node(|_modules|_modules.nosync|js)', '*.node', '.node-version'],
  nodemon: ['nodemon(|-debug).json'],
  npm: ['.npmrc'],
  npmIgnore: ['.npmignore'],
  nuxt: ['/.nuxt', '/nuxt', 'nuxt.config.js', 'nuxt.config.ts'],
  nuxtIgnore: ['.nuxtignore'],
  nvm: ['.nvmrc'],
  nx: ['nx.json'],
  nxIgnore: ['.nxignore'],
  ocaml: ['*.mli?'],
  onenote: ['*.one(|toc2)'],
  pages: ['*.pages'],
  partytown: ['partytown'],
  pdf: ['*.pdf'],
  percy: ['.percy.yml'],
  perl: ['/perl', '*.cgi', '*.pl', '*.plx', '*.pm', '*.pod', '*.t', '*.xs'],
  photoshop: ['*.psb', '*.psd'],
  php: ['/php', '*.phar', '*.php', '*.phps', '*.phpt', '*.pht', '*.phtml'],
  pine: ['*.pine'],
  plantuml: ['*.p(|lant)uml'],
  plasmic: ['/plasmic', 'plasmic.json'],
  plasmicLock: ['plasmic.lock'],
  playwright: ['playwright(|-ct).config.(js|mjs|ts)'],
  pnpm: ['.pnpmfile.cjs', 'pnpm-workspace.yaml'],
  pnpmLock: ['pnpm-lock.yaml'],
  poetryLock: ['poetry.lock'],
  post: ['*.(pc|s)ss'],
  postConfig: ['postcss(.config|rc).(js|ts|json)'],
  powerpoint: [
    '*.odp',
    '*.potm',
    '*.potx',
    '*.ppa',
    '*.ppam',
    '*.pps',
    '*.ppsm',
    '*.ppsx',
    '*.ppt',
    '*.pptm',
    '*.pptx',
  ],
  powershell: [
    '*.cdxml',
    '*.ps1',
    '*.ps1xml',
    '*.psc1',
    '*.psd1',
    '*.psm1',
    '*.psrc',
    '*.pssc',
  ],
  premiere: ['*.prproj'],
  prettier: [
    '.prettierrc(|.js|.cjs|.mjs|.json|.json5|.toml|.yml|.yaml)',
    'prettier.config.(|c|m)js',
  ],
  prettierIgnore: ['.prettierignore'],
  prisma: ['/prisma', '*.prisma'],
  processing: ['*.pde'],
  prolog: ['*.(p|pro|yap)'],
  protractor: ['protractor.conf(|ig).(j|t)s'],
  pug: ['*.(jade|pug)'],
  pugLint: ['.pug-lintrc(|.js|.json)'],
  purescript: ['*.purs'],
  pwa: ['*.webmanifest', 'manifest.json'],
  python: [
    '/.pytest_cache',
    '/__pycache__',
    '/pip',
    '/py',
    '/python',
    '*.py',
    '*.pyc',
    '*.pyd',
    '*.pyi',
    '*.pyo',
    '*.pyw',
    '*.pyz',
    '*.whl',
  ],
  pythonLint: ['.?pylintrc(|.toml)'],
  r: ['*.r', '*.rda', '*.rdata', '*.rds', '.rhistory'],
  racket: ['*.rkt'],
  rails: ['*.erb', 'rails'],
  railsApp: ['application.html.erb'],
  railsEdit: ['edit.html.erb'],
  railsIndex: ['index.html.erb'],
  railsJs: ['*.js.erb'],
  railsNew: ['new.html.erb'],
  railsShow: ['show.html.erb'],
  railsText: ['*.text.erb'],
  raku: [
    '*.p6',
    '*.pm6',
    '*.pod6',
    '*.raku',
    '*.rakudoc',
    '*.rakumod',
    '*.rakutest',
    '*.t6',
  ],
  react: ['/(jsx|vdom)', '/react(|-dom|-native)', '*.jsx'],
  reactTest: ['*.(cy|spec|spec-d|test|test-d).jsx', '*.jsx.snap'],
  reactTs: ['*.tsx'],
  reactTsTest: ['*.(cy|spec|spec-d|test|test-d).tsx', '*.tsx.snap'],
  reason: ['*.rei?'],
  rebol: ['*.reb'],
  red: ['*.reds?'],
  remix: ['remix.config.(js|cjs|mjs|ts)'],
  renovate: ['.renovaterc(|.json|.json5)', 'renovate.json5?'],
  replit: ['.replit'],
  rescript: ['*.res'],
  restql: ['*.r(|est)ql'],
  rexx: ['*.(exec|rex|rexx)'],
  riverpod: ['/riverpod'],
  rollup: ['rollup.config(|.common|.base|.dev|.prod).(js|cjs|mjs|ts)'],
  rspec: ['.?rspec'],
  rubocop: ['.rubocop(.yml|_todo.yml)'],
  ruby: ['/(gem|gems|ruby)', '*.(gem|gemspec|rake|rb)', 'rakefile'],
  rubyApp: ['app(|lication).rb'],
  rubyBoot: ['boot.rb'],
  rubyConfig: ['config.ru'],
  rubyController: ['application_controller.rb'],
  rubyDatabase: ['(schema|seeds).rb'],
  rubyEnv: ['(development|environment|production|test).rb'],
  rubyFile: ['assets.rb'],
  rubyFilter: ['filter_parameter_logging.rb'],
  rubyHelp: ['(application|rails|spec)_helper.rb'],
  rubyImport: ['importmap.rb'],
  rubyJob: ['application_job.rb'],
  rubyMail: ['application_mailer.rb'],
  rubyModel: ['application_record.rb'],
  rubyRoute: ['routes.rb'],
  rubyServer: ['puma.rb'],
  rubyVersion: ['(.ruby-version|version.rb)'],
  rust: ['/(.rustup|rs|rust)', '*.(rlib|rs)'],
  rustLib: ['lib.rs'],
  rustMain: ['main.rs'],
  rustModule: ['mod.rs'],
  sass: ['/s(a|c)ss', '*.s(a|c)ss'],
  sassApp: ['app(|lication).s(a|c)ss'],
  scala: ['/scala', '*.sc(|ala)'],
  scratch: ['*.(sb2|sb3|scratch|sprite|sprite2|sprite3)'],
  semaphore: ['/.semaphore'],
  semgrep: ['semgrep.ya?ml'],
  semgrepIgnore: ['.semgrepignore'],
  sentry: ['.sentryclirc'],
  shell: ['*.(awk|csh|fish|ksh|nu|sh|tcsh|zsh)'],
  sketch: ['*.sketch'],
  slim: ['*.slim'],
  smallbasic: ['*.(sb|smallbasic)'],
  snowpack: ['snowpack.config.(js|cjs|mjs|ts|json)'],
  solidity: ['*.sol'],
  sqlite: ['*.(s3db|db3|sl3|sqlite|sqlite3)'],
  storybook: [
    '*.stories.js',
    '*.stories.jsx',
    '*.stories.mdx',
    '*.stories.svelte',
    '*.stories.ts',
    '*.stories.tsx',
    '*.story.js',
    '*.story.jsx',
    '*.story.mdx',
    '*.story.ts',
    '*.story.tsx',
  ],
  stylelint: [
    '.stylelintcache',
    '.stylelintrc.cjs',
    '.stylelintrc.js',
    '.stylelintrc.json',
    '.stylelintrc.yaml',
    '.stylelintrc.yml',
    'stylelint.config.cjs',
    'stylelint.config.js',
  ],
  stylelintIgnore: ['.stylelintignore'],
  sublime: ['*.sublime-project', '*.sublime-workspace'],
  supabase: ['supabase.js', 'supabase.py'],
  svelte: ['*.svelte'],
  svelteConfig: ['svelte.config.cjs', 'svelte.config.js'],
  svg: [
    '/i',
    '/icns',
    '/ico',
    '/icon',
    '/icons',
    '/icos',
    '/svg',
    '/svgs',
    '*.svg',
    '*.svgz',
  ],
  swc: ['.swcrc'],
  swift: ['*.swift'],
  tailwind: ['tailwind.config.(js|cjs|mjs|ts)'],
  tauri: [
    'tauri(|.linux|.macos|.windows).toml',
    'tauri.(linux|macos|windows).conf.json',
    'tauri.conf(|ig).json5?',
  ],
  tcl: ['*.t(bc|cl)'],
  terraform: ['*.tf', '*.tfstate', '*.tfvars'],
  tex: ['*.(dtx|ltx|sty|tex)'],
  toml: ['*.toml'],
  tomlConfig: ['config.toml'],
  torrent: ['*.torrent'],
  touchicon: ['apple-touch-icon(|-precomposed).png'],
  travis: ['.travis.yml'],
  ts: ['/(@types|ts|types|typescript|typings)', '*.(|c|m)ts', 'tsc'],
  tsApp: ['app(|lication).ts'],
  tsComponent: ['*.component.ts'],
  tsConfig: ['tsconfig(.|-)(build|cjs|dts|e2e|esm|test).json', 'tsconfig.json'],
  tsController: ['*.controller.ts'],
  tsDef: ['*.d.ts'],
  tsError: ['*.(error|exception).ts'],
  tsFilter: ['*.filter.ts'],
  tsGuard: ['*.guard.ts'],
  tsInitializer: ['*.init.ts'],
  tsMain: ['(index|main).ts'],
  tsPipe: ['*.pipe.ts'],
  tsServer: ['*.server.ts'],
  tsService: ['*.service.ts'],
  tsStore: ['*.store.ts'],
  tsTest: ['*.(cy.ts|ts.snap)', '*.(e2e|e2e-spec|spec|test).(|c|m)ts'],
  tsWorker: ['(sw|serviceworker|service-worker|worker).ts'],
  turborepo: ['turbo.json'],
  unity: ['*.unity(|3d|packageweb)'],
  uno: ['uno(|css).config.(js|mjs|ts|mts)'],
  v: ['*.v', 'v.mod', 'vpkg.json'],
  vala: ['*.va(la|pi)'],
  vercel: ['/.now', '/.?vercel', '(now|vercel).json'],
  vercelIgnore: ['.(now|vercel)ignore'],
  verdaccio: ['verdaccio.ya?ml'],
  vim: ['*.vim', '.(ex|gvim|vim)rc', '.viminfo'],
  visio: [
    '*.vdw',
    '*.vsd',
    '*.vsdm',
    '*.vsdx',
    '*.vsl',
    '*.vss',
    '*.vssm',
    '*.vssx',
    '*.vst',
    '*.vstm',
    '*.vstx',
  ],
  visualbasic: ['*.vbs?'],
  visualstudio: [
    '*.csproj',
    '*.filters',
    '*.ruleset',
    '*.sln',
    '*.suo',
    '*.vcxitems',
    '*.vcxproj',
    '*.vsix',
    '*.vsixmanifest',
  ],
  vite: ['vite.config.(js|cjs|mjs|ts)'],
  vitest: [
    'vitest.config.(js|cjs|mjs|ts)',
    'vitest.(projects|workspace).(js|cjs|mjs|ts|json)',
  ],
  vmware: ['*.nvram', '*.scoreboard', '*.vmdk', '*.vmsd', '*.vmx'],
  vscode: [
    '/.vscode(|-server|-test)',
    '/vscode-extensions',
    '*.code-profile',
    '.vscode/(launch|settings|tasks).json',
  ],
  vscodeIgnore: ['.vscodeignore'],
  vue: ['/.vuepress', '/vue', '/vue-compat', '/vuejs', '*.vue'],
  vueConfig: ['(vetur|vue).config.(js|cjs|mjs|ts)'],
  wakatime: ['.wakatime-project', '.wakatime.cfg'],
  watchman: ['.watchmanconfig'],
  wasm: ['/wasm', '*.wasm'],
  wasmText: ['*.was?t'],
  webhint: ['.hintrc'],
  webpack: [
    '/webpack',
    'webpack.(js|cjs|mjs|ts)',
    'webpack(|.config).(babel|base|common|dev|prod|test).js',
  ],
  windi: ['*.windi', 'windi.config.(js|cjs|mjs|ts)'],
  windows: ['/(system32|win|windows)'],
  wolfram: ['*.wlt?'],
  word: [
    '*.doc',
    '*.docb',
    '*.docm',
    '*.docx',
    '*.dotm',
    '*.dotx',
    '*.odt',
    '*.rtf',
    '*.wbk',
  ],
  xaml: ['*.xaml'],
  xd: ['*.xd'],
  xml: [
    '*.classpath',
    '*.dtd',
    '*.entitlements',
    '*.iml',
    '*.jrxml',
    '*.manifest',
    '*.plist',
    '*.project',
    '*.resx',
    '*.tmlanguage',
    '*.xcscheme',
    '*.xcsettings',
    '*.xcworkspacedata',
    '*.xml',
    '*.xml.dist',
    '*.xml.dist.sample',
    '*.xquery',
    '*.xsd',
    '*.xsl',
    '*.xslt',
  ],
  yarn: ['.yarn(clean|-integrity|rc|rc.yml|rc.yaml)', 'yarn(|-error.log)'],
  yarnLock: ['yarn.lock'],
  yml: ['*.ya?ml', '*.yaml-tmlanguage'],
  ymlApp: ['app(|lication).ya?ml'],
  ymlCi: ['(check|checks|ci).ya?ml'],
  ymlDatabase: ['database.ya?ml'],
  ymlExample: ['*.(example|sample).ya?ml', '*.ya?ml.(example|sample)'],
  ymlFunding: ['funding.ya?ml'],
  ymlPublish: ['(publish|release).ya?ml'],
  ymlStorage: ['storage.ya?ml'],
  zenodo: ['.zenodo.json'],
  zig: ['/zig', '*.z(ig|ir|on)'],
}
